# See https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
title = "gitleaks config"

[extend]
useDefault = true

[[allowlists]]
description = "HuskyCI API repo: asset and vendor noise"
paths = [
  '''(.*?)(jpg|gif|doc|pdf|bin)$''',
  '''^vendor/(.*)$''',
  '''testdata/''',
  '''^.gitleaks\.toml$''',
]
